---
abstract: 'IRC plugin that fetches US weather by zip code'
author:
  - 'Curtis Brandt <curtis@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.023
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-WWW-Weather-US
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojo::UserAgent: 0
  POE::Component::IRC::Plugin: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Weather-US/issues
  homepage: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Weather-US
  repository: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Weather-US.git
version: 0.03
x_contributors:
  - 'Curtis Brandt <curtisjbrandt@gmail.com>'
